### ISSUE TITLE
No scroll feature under "Streams" while on safari 

### ISSUE THREAD

**Issue by mrahman313** [micro-nova/AmpliPi#834] opened 2024-07-26 15:22 UTC
Check out the video below. 

I have to zoom out on safari to click on spotify if I want a stream.

**Comment by mrahman313** [comment] 2024-07-26 15:23
Uploading RPReplay_Final1722007064.mp4…

**Comment by mrahman313** [comment] 2024-07-26 15:26
Uploading RPReplay_Final1722007064.mp4…

**Comment by mrahman313** [comment] 2024-07-26 15:27
https://github.com/user-attachments/assets/ae3fafde-6e8e-40c7-bc03-affe1c422d61

**Comment by rtertiaer** [comment] 2024-08-05 16:53
duplicate of #833

**Comment by rtertiaer** [comment] 2024-08-05 16:54
wait, I'm wrong.

**Closed** 2024-08-05 16:54 UTC
