### ISSUE TITLE
LMS streams not starting

### ISSUE THREAD

**Issue by SteveMicroNova** [micro-nova/AmpliPi#675] opened 2024-03-26 14:35 UTC
After I rebased to main while developing #664, LMS streams stopped starting properly and so I could no longer connect players to servers
After running the deploy script from the current state of main on a dev amplipi, I've found that this has been caused by a commit in the last 3 weeks as the streams started properly before rebasing

To define "not starting properly": They don't actually start at all, erroring out along the way. Ryan found it was something to do with a specific LMS config or file. I don't remember which, but I do know that the changes to scripts/configure.py in #664 led him towards finding the root of the issue

**Comment by rtertiaer** [comment] 2024-04-19 14:33
duplicate of #679 ?

**Comment by SteveMicroNova** [comment] 2024-04-19 14:35
Seems that way. Also both issues should be closed as the problem was solved when you bumped LMS versions

**Closed** 2024-04-19 14:36 UTC
Labels: bug, streaming, stability
