### ISSUE TITLE
Stream Type Selection Modal Doesn't Scroll

### ISSUE THREAD

**Issue by klay2000** [micro-nova/AmpliPi#866] opened 2024-08-06 13:06 UTC
The stream type selection modal isn't scroll-able and therefore breaks on smaller devices as shown in the screenshot below.
![image](https://github.com/user-attachments/assets/5d66bd66-39ff-4e99-b797-28a85c393ac5)

**Comment by rtertiaer** [comment] 2024-08-06 14:58
duplicate of #833; closing

**Closed by rtertiaer** 2024-08-06 14:58 UTC
